services:
  todo-api: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - 3004:3004
    links:
      - mongo
    volumes:
      - .:/myapi
    command: sh -c "npm install && npm run dev"
  mongo:
    image: mongo
    env_file: ./.env
    ports:
      - "${PORT_DB}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
